blog/urls.py
from django.urls import path
from .views import (
    UserPostListView,
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView
)
from . import views


urlpatterns = [
    path('posts', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('<int:post_id>', views.post, name='post'),
]

churches/urls.py
from django.urls import path
from .views import (
    UserChurchListView,
    ChurchListView,
    ChurchDetailView,
    ChurchCreateView,
    ChurchUpdateView,
    ChurchDeleteView,
    UservideoListView,
    videoListView,
    videoDetailView,
    videoCreateView,
    videoUpdateView,
    videoDeleteView
)
from . import views


urlpatterns = [
    path('church-list/', ChurchListView.as_view(), name='church-list'),
    path('user/<str:username>', UserChurchListView.as_view(), name='user-churches'),
    path('church/<int:pk>/', ChurchDetailView.as_view(), name='church-detail'),
    path('church/new/', ChurchCreateView.as_view(), name='church-create'),
    path('church/<int:pk>/update/', ChurchUpdateView.as_view(), name='church-update'),
    path('church/<int:pk>/delete/', ChurchDeleteView.as_view(), name='church-delete'),

    #videos urls
    path('video-list/', videoListView.as_view(), name='video-list'),
    path('user/<str:username>', UservideoListView.as_view(), name='user-videoes'),
    path('video/<int:pk>/', videoDetailView.as_view(), name='video-detail'),
    path('video/new/', videoCreateView.as_view(), name='video-create'),
    path('video/<int:pk>/update/', videoUpdateView.as_view(), name='video-update'),
    path('video/<int:pk>/delete/', videoDeleteView.as_view(), name='video-delete'),

]

plotx/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.contrib.auth import views as auth_views
from users import views as user_views
from users.views import *
from django.conf.urls import url



urlpatterns = [
    path('', include('pages.urls')),
    #path('accounts/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('churches/', include('churches.urls')),
    path('classes/', include('classes.urls')),
    path('exam_room/', include('exam_room.urls')),
    path('exercises/', include('exercises.urls'), name="excercises-urls"),
    path('notice_board/', include('notice_board.urls')),
    path('blog/', include('blog.urls')),
    path('realtors/', include('realtors.urls')),  
    path('companys/', include ('companys.urls')),  
    path('contact/', include('contact.urls')),
    path('listings/', include('listings.urls')),
    path('lessons/', include('lessons.urls')),
    path('users/', include('users.urls')),
    path('towns/', include('towns.urls')),
    path('locations/', include('locations.urls')),
    path('students/', include('students.urls')),
    path('subjects/', include('subjects.urls')),
    path('teachers/', include('teachers.urls')),
    path('videos/', include('videos.urls')),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
  
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/',
        auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
        ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
 
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    

churches/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from towns.models import Town
from members.models import Member
from locations.models import Location
from datetime import datetime

class Bg_color(models.Model):
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color

class Color(models.Model):
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color

class Hover_color(models.Model):
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color

class Hover_border_color(models.Model):
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color

class Hover_text_color(models.Model):
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color

class Border_color(models.Model):
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color



class Text_color(models.Model):
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color

class Footer_color(models.Model):
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color

class Church_denomination(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name



 

# Create your models here.
class Church(models.Model):
    church_name = models.CharField(max_length=100, blank=True, null=True, unique=True)
    church_denomination = models.ForeignKey(Church_denomination, on_delete=models.DO_NOTHING,  blank=True, null=True, help_text='optional')
    contact_person = models.CharField(max_length=100, blank=False, null=True)
    churchmember = models.ManyToManyField(Member, blank=True, help_text="Select this church members")
    church_slogan = models.CharField(max_length=200, blank=True, null=True)
    town = models.ForeignKey(Town, on_delete=models.DO_NOTHING, blank=True, null=True,  help_text="Select The exact towns where this church is located")
    location = models.ForeignKey(Location, on_delete=models.DO_NOTHING, blank=True, null=True, help_text="Select The exact locations where this Church  is found in the choosen Town")
    church_pic =  models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, null=True)
    logo = models.ImageField(default='logo.png', upload_to='logos/%Y/%m/%d/', blank=True, null=True)
    about_pic = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, null=True )
    service_pic = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, null=True )
    about_church = RichTextField(max_length=1500, blank=False, null=True, help_text="Max 200 words")
    services = RichTextField(max_length=1500, blank=False, null=True, help_text="Max 200 words")
    bg_color = models.ForeignKey(Bg_color, on_delete=models.DO_NOTHING,  blank=True, null=True, help_text='optional')
    hover_color = models.ForeignKey(Hover_color, on_delete=models.DO_NOTHING,  blank=True, null=True, help_text='optional')
    border_color = models.ForeignKey(Border_color, on_delete=models.DO_NOTHING,  blank=True, null=True, help_text='optional')
    color = models.ForeignKey(Color, on_delete=models.DO_NOTHING,  blank=True, null=True, help_text='optional')
    text_color = models.ForeignKey(Text_color, on_delete=models.DO_NOTHING,  blank=True, null=True, help_text='optional')
    footer_color = models.ForeignKey(Footer_color, on_delete=models.DO_NOTHING,  blank=True, null=True, help_text='optional')
    email_1 = models.CharField(max_length=100, blank=True, null=True)
    email_2 = models.CharField(max_length=100, blank=True, null=True)
    phone_1 = models.CharField(max_length=100, blank=True, null=True)
    phone_2 = models.CharField(max_length=100, blank=True, null=True)
    phone_2 = models.CharField(max_length=100, blank=True, null=True)
    facebook = models.CharField(max_length=100, blank=True, null=True)
    twitter = models.CharField(max_length=100, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    youtube = models.CharField(max_length=100, blank=True, null=True)
    Instagram = models.CharField(max_length=100, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    is_thika = models.BooleanField(default=False)
    is_ruiru = models.BooleanField(default=False)
    is_maimahiu = models.BooleanField(default=False)
    is_kiambu = models.BooleanField(default=False)
    is_gatundu = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse('church-detail', args=[str(self.id)])

    def __str__(self):
        return self.church_name




STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Photo(models.Model):
    name= models.CharField(max_length=500)
    description = RichTextField(blank=False, null=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=False, null=True)
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, null=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, null=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, null=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, null=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, null=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, null=True)
    church = models.ForeignKey(Church, on_delete=models.DO_NOTHING, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=False, null=True)
    def __str__0(self):
        return self.name

class Video(models.Model):
    name= models.CharField(max_length=500)
    videofile= models.FileField(upload_to='videos/', null=True, blank=True)
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True, null=True)
    description = RichTextField(blank=False, null=True)
    church = models.ForeignKey(Church, on_delete=models.DO_NOTHING, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=False, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.name

class Weekly_theme(models.Model):
    church = models.ForeignKey(Church, on_delete=models.DO_NOTHING, blank=True, null=True)
    title = models.CharField(max_length=200, blank=False, null=True)
    text = RichTextField(max_length=4000, blank=True, null=True)
    #status = models.IntegerField(choices=STATUS, default=0)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=False, null=True)
    pub_date = models.DateTimeField(default=timezone.now)
    is_published = models.BooleanField(default=True)
    def __str__(self):
        return self.title

class Theme_of_the_year(models.Model):
    text = models.CharField(max_length=1000)
    church = models.ForeignKey(Church, on_delete=models.DO_NOTHING, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=False, null=True)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.church.church_name  

class Daily_word(models.Model):
    title = models.CharField(max_length=200, blank=False, null=True)
    church = models.ForeignKey(Church, on_delete=models.DO_NOTHING, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=False, null=True)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.church.church_name  
   
    
class Schedule(models.Model):
    church = models.ForeignKey(Church, on_delete=models.DO_NOTHING, blank=True, null=True)
    title = models.CharField(max_length=200, blank=False, null=True)
    orderofservice = RichTextField(blank=True, null=True)
    praiseandworship = models.CharField(max_length=100, blank=True,null=True)
    ministering_choir = models.CharField(max_length=100, blank=True, null=True)
    first_service_leader = models.CharField(max_length=200, blank=True, null=True)
    second_service_leader = models.CharField(max_length=200, blank=True, null=True)
    todays_speaker_1 = models.CharField(max_length=200, blank=True, null=True)
    todays_speaker_2 = models.CharField(max_length=200, blank=True, null=True)
    Service_date = models.DateTimeField(default=datetime.now, blank=True)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=False, null=True)
    pub_date = models.DateTimeField(default=timezone.now)
    is_published = models.BooleanField(default=True)
    def __str__(self):
        return self.title

class Announcement(models.Model):
    church = models.ForeignKey(Church, on_delete=models.DO_NOTHING, blank=True, null=True)
    title = models.CharField(max_length=200, blank=False, null=True)
    announcement = RichTextField(null=True, blank=True)
    announcement_date = models.DateTimeField(default=timezone.now)
    pub_date = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, blank=False, null=True)
    is_published = models.BooleanField(default=True)
    def __str__(self):
        return self.title



class Home_cell(models.Model):
    church = models.ForeignKey(Church, on_delete=models.DO_NOTHING, blank=True, null=True)
    cell_location = models.CharField(max_length=200, blank=False, null=True)
    cell_day = models.CharField(max_length=200, blank=False, null=True)
    cell_leader = models.CharField(max_length=200, blank=False, null=True)

templates/churches/_church.html
{% load static %}
<style>
    div.bz {
        display: inline-block;
        /*--width: 110px;
        height: 110px;
        margin: 10px;--*/
        --aug-border: 5px;
        --aug-inset: 5px;
        padding: 10px; /* mind the gap */
        text-align: center;
        /*--aug-border-bg: gold;
        --aug-inset-bg: gold;*/
    }
    div.bz0 {
        --aug-tr-height: 30%;
    }

    div.bz1 {
        --aug-tr-height: 30%;
        --aug-border-radius-fallback-inset: 20px 0px 5px 0px;
    }

    div.bz2 {
        --aug-br: 25px;
        --aug-l-height: 57%;
        --aug-l-width: 10px;
    }

</style>

{% if church_list %}
<div class=" w3-margin-top w3-margin-bottom w3-row-padding"  style="list-style-type: none;" id="myUL">  
    <div class="w3-padding"></div>
  
    {% for church in church_list %} 
 
    <!--large view-->
    <div class="w3-col l6 m6 w3-hide-small">
      <a href="{{ church.get_absolute_url }}">
        <div augmented-ui="br-clip-y l-clip-y  exe" class="btn bz bz2 w3-border w3-container {{church.bg_color }} {{church.border_color}}  w3-card-4 w3-padding  w3-large  w3-hover-shadow " style="width:100%; margin:5px; padding:5px 3px;">
          <div class="" style="width:20%; float:left">
            <img src="{{ church.logo.url }}" alt="" class="w3-white w3-circle w3-border w3-padding w3-border-khaki w3-card-4 " style="width: 80px; height:70px;">
          </div>
          <div class="" style="width:80%; float:right">
            <span class="w3-large w3-wide ">{{ church.church_name }}</span>
            <br> <span class="w3-small">{{church.church_type}}</span>    
                <span class="w3-small">[{{church.town}}]</span>
            <span class="w3-small w3-hide w3-right">reviews</span>
          </div>
        </div>
      </a>
    </div>
  

    
    {% endfor %}
  </div>
 
  {% else %}
      <p>There are no churchs available.</p>
  {% endif %}


  <!--Small View-->

  {% if church_list %}
 <div class=" w3-hide-large w3-hide-medium">
  {% for church in church_list %} 
 
      <a href="{{ church.get_absolute_url }}">
        <div augmented-ui="br-clip-y l-clip-y  exe"  class="btn  w3-border bz bz2 {{church.bg_color}}  {{church.border_color}}  w3-margin-bottom w3-large  w3-hover-shadow" style="width:100%; ">
          <div class="" style="width:20%; float:left">
            <img src="{{ church.logo.url }}" alt="" class="w3-white   w3-circle w3-card-4 w3-border w3-padding w3-border-khaki " style="width: 75px; height:65px;">
          </div>
          <div class="" style="width:80%; float:right">
            <span class="w3-large ">{{ church.church_name }}</span>
            <br> <span class="w3-small">{{church.church_type}}</span>
                <span class="w3-small">[ {{church.town}} ]</span>
            <span class="w3-small w3-hide w3-right">reviews</span>
          </div>
        </div>
      </a>
    {% endfor %}
  </div>
  {% else %}
      <p>There are no churchs available.</p>
  {% endif %}

templates/churches/_churchcontact.html
<div class="w3-display-container">
  <div class=" {{church.bg_color}} w3-margin-top w3-opacity-min">
    <div class="w3-padding w3-margin">
      <h1 class="w3-xxlarge w3-text-white w3-center">Contact</h1> 
      <p class="w3-center w3-text-white">send us a message we would love to hear from you</p>
    </div>
    <div class="container">
        <div class="modal-body">
          <form action="{% url 'church-contact' %}" method="POST">
            {% csrf_token %}
            {% if user.is_authenticated %}
              <input type="hidden" name="user_id" value="{{ user.id }}">
            {% else %}
              <input type="hidden" name="user_id" value="0">
            {% endif %}
            <input type="hidden" name="church_email" value="{{ church.email }}">
            <input type="hidden" name="church_id" value="{{ church.id }}">
            
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-12">
                                    <label for="church_name" class="col-form-label">church:</label>
                                    <input type="text" name="church" class="form-control" value="{{ church.church_name }}">
                                </div>
                                <div class="col-sm-12"> 
                                    <label for="name" class="col-form-label">First Name:</label>
                                    <input type="text" name="name" class="form-control" {% if user.is_authenticated %} value="{{ user.username }}" {% endif %} required>
                                </div>

                                <div class="col-sm-12">
                                    <label for="phone" class="col-form-label">Phone:</label>
                                    <input type="text" name="phone" class="form-control">
                                </div>
                                <div class="col-sm-12"> 
                                    <label for="email" class="col-form-label">Email:</label>
                                    <input type="email" name="email" class="form-control" {% if user.is_authenticated %} value="{{ user.email }}" {% endif %} required>
                                </div>
                            </div>
                        </div>
                    </div>
             
                    <div class="col-sm-6">
                        <div class="form-group">
                            <div class="row">  
                                    <label for="header" class="col-form-label">Message heading:</label>
                                    <input type="text" name="header" class="form-control">
                                    <br>
                                    <label for="message" class="col-form-label">Message:</label>
                                    <textarea name="message" class="form-control" style="min-height:180px;"></textarea>
                            </div>
                        </div>
                    </div>
                </div>

            <input type="submit" value="Send" class="btn btn-block w3-hover-white w3-hover-shadow w3-border w3-border-white {{church.hover_text_color}} {{church.bg_color}}">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
<div>

</div>

templates/churches/_header.html
 <!--Medium-->
 <div class="header " style="width:100%; height:70%; background-repeat: no-repeat; background-image: url({{ church.church_pic.url }});">

    <!--Content before waves-->
    <div class="inner-header flex ">
    <!--Just the logo.. Don't mind this-->
    <div class="w3-display-container ">
      <div class=" w3-display-leftbottom {{church.border_color}} w3-margin"> 
        {% include 'churches/_logo.html' %}
    </div>

  </div>  
    
  
    </div>
  
    
    <!--Waves Container-->
    <div>
    <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
    viewBox="0 24 150 28" preserveAspectRatio="none" shape-rendering="auto">
    <defs>
    <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
    </defs>
    <g class="parallax">
    <use xlink:href="#gentle-wave" x="48" y="0" fill="rgba(255,255,255,0.7" />
    <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.5)" />
    <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.3)" />
    <use xlink:href="#gentle-wave" x="48" y="7" fill="#fff" />
    </g>
    </svg>
    </div>
    <!--Waves end-->
    
    </div>
    
    <!--Header ends-->
    
    <!--Content starts-->
        {% include 'partials/_alerts.html' %} 
      <div class="w3-light-grey">
        {% for theme_of_the_year in church.theme_of_the_year_set.all %}
          <h4 class="w3-center w3-xlarge w3-hide-small {{church.text_color}}">{{theme_of_the_year.text}}</h4>
          <h4 class="w3-center w3-large w3-hide-large w3-hide-medium {{church.text_color}}">{{theme_of_the_year.text}}</h4>
        {% endfor %}
        <p class="w3-center" ><strong>{{ church.church_slogan|upper }}</strong> </p>
      </div>
  
    
    <!--Content ends-->

templates/churches/_schedule.html
<div class="w3-hide-small">
{% for schedule in church.schedule_set.all %}
<h3 class="w3-center w3-hide-samll w3-paddding {{church.text_color}}">ORDER OF SERVICES</h3>
<h5 class="{{church.text_color}} w3-center">Sunday {{schedule.Service_date}}</h5>
<div class="w3-row section w3-padding "  >
  <br>


  <div class="w3-col l6 m6 w3-border w3-sand w3-container {{church.border_color}} w3-rightbar" style="height: 500px;">
    <br>
    <div class="w3-center  {{church.text_color}} w3-margin"> {{ schedule.orderofservice|safe }}</div>
  </div>
  
  <div class="w3-col l6 m6 w3-border w3-sand w3-card-4 {{church.border_color}} w3-leftbar" style="height: 500px;">
    <br>
    <div class="w3-center">
     <div class="w3-margin">
     {% if schedule.praiseandworship %}
     <h5><u>Praise & Worship</u></h5>
      <span class="{{church.text_color}} w3-large">{{schedule.praiseandworship}}</span>
     {% endif %}
      
      
      {% if schedule.ministering_choir %}
      <h5><u>Ministering Choir</u></h5>
      <span class="{{church.text_color}} w3-large">{{schedule.ministering_choir}}</span>
      {% endif %}
     </div>

      <div class="w3-padding">
      {% if schedule.first_service_leader %}
      <h5><u>Service Leader</u></h5>
      <span class="{{church.text_color}} w3-large">{{schedule.first_service_leader}}</span><br>
      {% endif %}

      {% if schedule.second_service_leader %}
      <span class="{{church.text_color}} w3-large">{{schedule.second_service_leader}}</span>
      {% endif %}
      </div>

      <div class="w3-padding">
      {% if schedule.todays_speaker_1 %}
      <h5><u>Today Speakers</u></h5>
      <span class="{{church.text_color}} w3-large">{{schedule.todays_speaker_1}}</span><br>
      {% endif %}

      {% if schedule.todays_speaker_2 %}
      <span class="{{church.text_color}} w3-large">{{schedule.todays_speaker_2}}</span>
      {% endif %}
    </div>
    </div>
  </div>
</div>
{% endfor %}
</div>

<div class="w3-hide-large w3-hide-medium">
  {% for schedule in church.schedule_set.all %}
  <h3 class="w3-center w3-paddding {{church.text_color}}">ORDER OF SERVICES</h3>
  <h5 class="{{church.text_color}} w3-center">Sunday {{schedule.Service_date}}</h5>
  <div class="w3-row section w3-padding "  >
    <br>
    <div class="w3-col l6 m6  w3-white {{church.border_color}} w3-topbar" style="height: 500px;">
      <br>
      <div class="w3-center  {{church.text_color}} w3-margin"> {{ schedule.orderofservice|safe }}</div>
    </div>
    <div class="w3-col l6 m6  w3-white {{church.border_color}} w3-bottombar" style="height: 500px;">
      <br>
      <div class="w3-center">
       <div class="w3-margin">
       {% if schedule.praiseandworship %}
       <h5><u>Praise & Worship</u></h5>
        <span class="{{church.text_color}} w3-large">{{schedule.praiseandworship}}</span>
       {% endif %}
        
        
        {% if schedule.ministering_choir %}
        <h5><u>Ministering Choir</u></h5>
        <span class="{{church.text_color}} w3-large">{{schedule.ministering_choir}}</span>
        {% endif %}
       </div>
  
        <div class="w3-padding">
        {% if schedule.first_service_leader %}
        <h5><u>Service Leader</u></h5>
        <span class="{{church.text_color}} w3-large">{{schedule.first_service_leader}}</span><br>
        {% endif %}
  
        {% if schedule.second_service_leader %}
        <span class="{{church.text_color}} w3-large">{{schedule.second_service_leader}}</span>
        {% endif %}
        </div>
  
        <div class="w3-padding">
        {% if schedule.todays_speaker_1 %}
        <h5><u>Today Speakers</u></h5>
        <span class="{{church.text_color}} w3-large">{{schedule.todays_speaker_1}}</span><br>
        {% endif %}
  
        {% if schedule.todays_speaker_2 %}
        <span class="{{church.text_color}} w3-large">{{schedule.todays_speaker_2}}</span>
        {% endif %}
      </div>
      </div>
    </div>
  </div>
  {% endfor %}
  </div>

templates/churches/_weeklytheme.html
{% for weekly_theme in church.weekly_theme_set.all %}
<div class="w3-display-container bgimg-1" style="padding:64px 16px; min-height: 400px;"  >
  <div class="w3-display-middle {{church.bg_color}} w3-padding w3-opacity-min">

   <!--large devices-->
    <div class="w3-border w3-hide-small w3-border-white w3-padding w3-margin">
      <h3 class="w3-center w3-text-white w3-wide w3-xxlarge">This Week Theme<br></h3>
      <div class="w3-center col-sm"><span class="w3-xlarge" >A Message from your Pastor</span></div>
    </div>

   <!--small devices-->
   <div class="w3-border w3-hide-large w3-hide-medium w3-border-white w3-padding w3-margin">
      <h3 class="w3-center w3-text-white w3-wide w3-xlarge">This Week Theme<br></h3>
      <div class="w3-center col-sm"><span class="w3-large" >A Message from your Pastor</span></div>
  </div>
  </div>
</div>
  <div class="w3-content container w3-padding">
   {{weekly_theme.text|safe}}
    </div>
  </div>
  {% endfor %}